export default function Terms() {
    return (
        <div>
            <h1><b>Terms and Conditions of Use</b></h1>
            <p>Welcome to the ACE web site at acefitness.org. ACE provides its services to you subject to the following Terms and Conditions. If you visit, use a service, or make purchases at acefitness.org or any of our other web sites (collectively, the “Site”) operated by the American Council on Exercise or one of its divisions or subsidiaries (collectively, “ACE”), you agree to abide by these Terms and Conditions when you use the Site. If you do not agree to these Terms and Conditions of Usage, do not use any portion of the Site. ACE reserves the right to revise these Terms and Conditions at any time by updating these Terms and Conditions of Use. Your continued use of the Site constitutes your agreement to comply with such revisions, so please visit this page from time to time.</p>

            <h2><b>1. Nonexclusive License</b></h2>
            <p>We grant you a nonexclusive, nontransferable, limited right to access and display the Site and the material provided herein for personal use, provided that you comply fully with these Terms and Conditions of Use. No portion of the Site may be reproduced, duplicated, copied, sold, resold, visited, or otherwise exploited for any commercial purpose without the express prior written consent of ACE. You may not frame or utilize framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of ACE without our express prior written consent. You may not use any meta tags or any other "hidden text" utilizing ACE's name or trademarks without the express prior written consent of ACE. Any unauthorized use terminates the rights granted herein by ACE. You are granted a limited, revocable, and nonexclusive right to create a hyperlink to the home page of the Site so long as the link does not portray ACE, its affiliates, or their products or services in a false, misleading, derogatory, or otherwise offensive matter. You may not use any ACE logo or other proprietary graphic or trademark as part of the link without the express prior written permission of ACE.</p>

            <h3><b>2. Prohibited Uses</b></h3>
            <p>Unauthorized use or modification of any information stored on the Site may result in criminal and/or civil prosecution under applicable Federal, State and local laws. You may not use the Site for anything other than a lawful and legitimate purpose. You agree not to use the Site to (i) promote any unlawful activity or purpose, including without limitation, any activity that could give rise to criminal or civil liability; (ii) carry out any unauthorized alteration of any data or information on or supplied by another user of the Site; or (iii) conduct any activity that infringes on the copyright, patent, trademark, service mark or other rights of any person or entity. You shall not restrict or inhibit any other user from using and enjoying any service conducted on the Site. You are solely responsible for the content of any transmissions you make to the Site or to any ACE employee.
            You agree that you will not send, post or otherwise publish through the Site, any message, material, user name or other communication that: (i) is unlawful, offensive, obscene, vulgar, indecent, pornographic, profane, sexually-oriented, threatening, abusive, false or misleading with respect to origin or fact, slanderous, libelous or defamatory; (ii) impersonates any person or entity; (iii) provides personally identifiable information of any person or entity such as an address or phone number; (iv) constitutes or encourages the conduct of a criminal offense; (v) gives rise to liability; (vi) promotes the use of controlled substances; (vii) causes injury of any kind to any person or entity; (viii) infringes or violates the intellectual property rights, contract rights, or any other rights of any third party; (ix) contains harmful or malicious components or code designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment; or (x) creates a link to another Site. You agree not to interrupt, or attempt to interrupt, the operation of the Site in any way. You may not advertise or solicit on or through the Site without the express prior written permission of ACE. You agree that you will not use the Site for chain letter, junk mail, “spamming,” solicitations (commercial or non-commercial) or bulk communications of any kind including, but not limited to, distribution lists to any person who has not given specific permission to be included in such a list.</p>

            <h4><b>3. Usage and Monitoring</b></h4>
            <p>If you use this Site, you are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer, and you agree to accept responsibility for all activities that occur under your account or password. ACE does sell products for children. If you are under 18, you may use ACEfitness.org only with involvement of a parent or guardian. ACE reserves the right to refuse service, terminate accounts, remove or edit content, or cancel orders in its sole discretion. While ACE has no obligation to monitor the Site and is not responsible for the content of any messages, information or files transmitted on the Site, ACE reserves the right to delete and take other appropriate action with respect to such messages, information or files with which ACE, in its sole and absolute discretion, deems objectionable or otherwise in violation of these Terms and Conditions. ACE further reserves the right, in its sole and absolute discretion and without notice, to deny access to the Site to anyone at any time.
            If you do post or submit content of any nature, and unless indicated otherwise, you grant ACE a nonexclusive, royalty-free, perpetual, irrevocable, and fully sub-licensable right to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, and display such content throughout the world in any media now known or hereinafter invented. You also grant ACE the right to use the name that you submit in connection with such content. You represent and warrant that you own or otherwise control all of the rights to the content that you submit; that the content is accurate; that use of the content you supply does not violate any rights and will not cause injury to any person or entity; and that you will fully indemnify ACE for all claims of any nature resulting from content you supply. ACE respects the intellectual property of others. If you believe that your material has been copied in a way that constitutes copyright or trademark infringement, please notify us immediately.</p>

            <h5><b>4. Privacy</b></h5>
            <p>Your use of the Site constitutes your consent to ACE's privacy policy posted on the Site which is updated from time to time. You may review the current ACE privacy policy at www.acefitness.org/legal/privacy-policy.</p>

            <h6><b>5. Copyright Ownership</b></h6>
            <p>All content included on this Site, including but not limited to text, graphics, photographs, logos, and software, and all derivative rights thereof is the property of ACE or its content suppliers and is protected by United States and international copyright laws. Unauthorized copying, reproduction, republishing, uploading, downloading, posting, transmitting or duplicating any of the material is prohibited. ACE and its content suppliers do not grant any express or implied rights to you under any patents, copyrights, trademarks or trade secrets.

To manage your copyright on ACEfitness.org, please contact us at:

Email: copyright@ACEfitness.org

Phone: (800) 825-3636

Address:

9444 Balboa Ave. Suite 290
San Diego, CA 92123-4901</p>
        </div>
    )
}